title: Sakshi Sharma
email: 
description: >- 
  Ph.D. scholar in AI & Education | AIML
baseurl: "" # e.g. /sakshi-site if hosting under a subpath
url: "https://sakshivk.github.io" # replace with your GitHub Pages URL


remote_theme: "jekyll/minima@1e8a445"


# Optional social links
social_links:
  - name: GitHub
    url: https://github.com/imsakshivk
  - name: LinkedIn
    url: https://www.linkedin.com/in/sakshivk

# Optional build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme # add this line to the plugins list if you already have one
